### ISSUE TITLE
Install.ps1 doesn't run properly

### ISSUE THREAD

**Issue by lukiiimohh** [stonedDiscord/RealAndroidBot#7]
Whenever I click on "Run with powershell" at `Install.ps1` it pops up with a terminal but inmediatly closes it. Can't get further than this step.

Also I am on W11 (idk if this is the reason)

**Comment by stonedDiscord** [comment]
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.3
